allowBuilds:
  cwebp-bin: set this to true or false
  esbuild: true
  gifsicle: set this to true or false
  jpegtran-bin: set this to true or false
  mozjpeg: set this to true or false
  optipng-bin: set this to true or false
  pngquant-bin: set this to true or false
