/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WachtlijstRouteImport } from './routes/wachtlijst'
import { Route as StoryRouteImport } from './routes/story'
import { Route as FlavorsRouteImport } from './routes/flavors'
import { Route as IndexRouteImport } from './routes/index'

const WachtlijstRoute = WachtlijstRouteImport.update({
  id: '/wachtlijst',
  path: '/wachtlijst',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryRoute = StoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => rootRouteImport,
} as any)
const FlavorsRoute = FlavorsRouteImport.update({
  id: '/flavors',
  path: '/flavors',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/flavors': typeof FlavorsRoute
  '/story': typeof StoryRoute
  '/wachtlijst': typeof WachtlijstRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/flavors': typeof FlavorsRoute
  '/story': typeof StoryRoute
  '/wachtlijst': typeof WachtlijstRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/flavors': typeof FlavorsRoute
  '/story': typeof StoryRoute
  '/wachtlijst': typeof WachtlijstRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/flavors' | '/story' | '/wachtlijst'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/flavors' | '/story' | '/wachtlijst'
  id: '__root__' | '/' | '/flavors' | '/story' | '/wachtlijst'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FlavorsRoute: typeof FlavorsRoute
  StoryRoute: typeof StoryRoute
  WachtlijstRoute: typeof WachtlijstRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wachtlijst': {
      id: '/wachtlijst'
      path: '/wachtlijst'
      fullPath: '/wachtlijst'
      preLoaderRoute: typeof WachtlijstRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story': {
      id: '/story'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof StoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flavors': {
      id: '/flavors'
      path: '/flavors'
      fullPath: '/flavors'
      preLoaderRoute: typeof FlavorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FlavorsRoute: FlavorsRoute,
  StoryRoute: StoryRoute,
  WachtlijstRoute: WachtlijstRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
